INSERT INTO CUSTOMER (NAME) VALUES ('Anders');
INSERT INTO CUSTOMER (NAME) VALUES ('Benjamin');
INSERT INTO CUSTOMER (NAME) VALUES ('Carsten');
INSERT INTO CUSTOMER (NAME) VALUES ('Dorthe');
INSERT INTO CUSTOMER (NAME) VALUES ('Erik');
INSERT INTO CUSTOMER (NAME) VALUES ('Frank');
INSERT INTO CUSTOMER (NAME) VALUES ('Gertrud');
INSERT INTO CUSTOMER (NAME) VALUES ('Hans');